spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:sqlite:./pubgolf.db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor: TRACE

application:
  origins:
    - http://localhost:3000
    - http://192.168.18.47:3000
