spring:
  datasource:
    url: jdbc:sqlite:/data/pubgolf.db
    driver-class-name: org.sqlite.JDBC

application:
  origins:
    - https://pubgolf.suskins.co.uk
    - https://www.pubgolf.me
    - https://pubgolf.me
